package com.botrom.hoshimi_ca_mod.registry;

import com.botrom.hoshimi_ca_mod.HoshimiCulinaryMod;
import com.botrom.hoshimi_ca_mod.utils.Utils;
import net.minecraft.core.Holder;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.sounds.SoundEvent;
import net.minecraft.sounds.SoundEvents;
import net.minecraft.world.level.block.SoundType;
import net.minecraftforge.common.util.ForgeSoundType;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

import java.util.function.Supplier;

public class ModSounds
{
    public static final DeferredRegister<SoundEvent> SOUND_EVENTS = DeferredRegister.create(ForgeRegistries.SOUND_EVENTS, HoshimiCulinaryMod.MOD_ID);

    public static final RegistryObject<SoundEvent> BUBBLE_POP = createSoundEvent("bubble_pop");
    public static final RegistryObject<SoundEvent> LOBSTER_HURT = createSoundEvent("entity/lobster_hurt");
    public static final RegistryObject<SoundEvent> LOBSTER_ATTACK = createSoundEvent("entity/lobster_attack");
    public static final RegistryObject<SoundEvent> GIANT_SQUID_GAMES = createSoundEvent("entity/giant_squid_games");
    public static final RegistryObject<SoundEvent> GIANT_SQUID_HURT = createSoundEvent("entity/giant_squid_hurt");
    public static final RegistryObject<SoundEvent> GIANT_SQUID_TENTACLE = createSoundEvent("entity/giant_squid_tentacle");
    public static final RegistryObject<SoundEvent> COMB_JELLY_HURT = createSoundEvent("entity/comb_jelly_hurt");
    public static final RegistryObject<SoundEvent> MIMIC_OCTOPUS_IDLE = createSoundEvent("entity/mimic_octopus_idle");
    public static final RegistryObject<SoundEvent> MIMIC_OCTOPUS_HURT = createSoundEvent("entity/mimic_octopus_hurt");
    public static final RegistryObject<SoundEvent> SEAGULL_IDLE = createSoundEvent("entity/seagull_idle");
    public static final RegistryObject<SoundEvent> SEAGULL_HURT = createSoundEvent("entity/seagull_hurt");
    public static final RegistryObject<SoundEvent> HUMMINGBIRD_IDLE = createSoundEvent("entity/hummingbird_idle");
    public static final RegistryObject<SoundEvent> HUMMINGBIRD_HURT = createSoundEvent("entity/hummingbird_hurt");
    public static final RegistryObject<SoundEvent> HUMMINGBIRD_LOOP = createSoundEvent("entity/hummingbird_loop");
    public static final RegistryObject<SoundEvent> CROW_IDLE = createSoundEvent("entity/crow_idle");
    public static final RegistryObject<SoundEvent> CROW_HURT = createSoundEvent("entity/crow_hurt");
    public static final RegistryObject<SoundEvent> MANTIS_SHRIMP_SNAP = createSoundEvent("entity/mantis_shrimp_snap");
    public static final RegistryObject<SoundEvent> MANTIS_SHRIMP_HURT = createSoundEvent("entity/mantis_shrimp_hurt");
    public static final RegistryObject<SoundEvent> CACHALOT_WHALE_IDLE = createSoundEvent("entity/cachalot_whale_idle");
    public static final RegistryObject<SoundEvent> CACHALOT_WHALE_HURT = createSoundEvent("entity/cachalot_whale_hurt");
    public static final RegistryObject<SoundEvent> CACHALOT_WHALE_CLICK = createSoundEvent("entity/cachalot_whale_click");
    public static final RegistryObject<SoundEvent> TERRAPIN_HURT = createSoundEvent("entity/terrapin_hurt");
    public static final RegistryObject<SoundEvent> MUDSKIPPER_HURT = createSoundEvent("entity/mudskipper_hurt");
    public static final RegistryObject<SoundEvent> MUDSKIPPER_WALK = createSoundEvent("entity/mudskipper_walk");
    public static final RegistryObject<SoundEvent> MUDSKIPPER_SPIT = createSoundEvent("entity/mudskipper_spit");
    public static final RegistryObject<SoundEvent> SHIBA_EAT_ARROW = createSoundEvent("entity/shiba_eat_arrow");
    public static final RegistryObject<SoundEvent> SHIBA_WHINE = createSoundEvent("entity/shiba_whine");
    public static final RegistryObject<SoundEvent> SHIBA_STEP = createSoundEvent("entity/shiba_step");
    public static final RegistryObject<SoundEvent> SHIBA_AMBIENT = createSoundEvent("entity/shiba_ambient");
    public static final RegistryObject<SoundEvent> SHIBA_PANT = createSoundEvent("entity/shiba_pant");
    public static final RegistryObject<SoundEvent> SHIBA_HURT = createSoundEvent("entity/shiba_hurt");
    public static final RegistryObject<SoundEvent> SHIBA_DEATH = createSoundEvent("entity/shiba_death");
    public static final RegistryObject<SoundEvent> CHESTER_IDLE = createSoundEvent("entity/chester_idle");
    public static final RegistryObject<SoundEvent> CHESTER_JUMP = createSoundEvent("entity/chester_jump");
    public static final RegistryObject<SoundEvent> CHESTER_HURT = createSoundEvent("entity/chester_hurt");
    public static final RegistryObject<SoundEvent> CHESTER_DEATH = createSoundEvent("entity/chester_death");
    public static final RegistryObject<SoundEvent> CHESTER_OPEN_MOUTH = createSoundEvent("entity/chester_open_mouth");
    public static final RegistryObject<SoundEvent> CHESTER_CLOSE_MOUTH = createSoundEvent("entity/chester_close_mouth");
    public static final RegistryObject<SoundEvent> SHIMA_ENAGA_AMBIENT = createSoundEvent("entity/shima_enaga_ambient");
    public static final RegistryObject<SoundEvent> TORTOISE_HIDE = createSoundEvent("entity/tortoise_hide");
    public static final RegistryObject<SoundEvent> TORTOISE_THUD = createSoundEvent("entity/tortoise_thud");
    public static final RegistryObject<SoundEvent> TORTOISE_HURT = createSoundEvent("entity/tortoise_hurt");
    public static final RegistryObject<SoundEvent> TORTOISE_DEATH = createSoundEvent("entity/tortoise_death");
    public static final RegistryObject<SoundEvent> SNAIL_CRUSH = createSoundEvent("entity/snail_crush");
    public static final RegistryObject<SoundEvent> SNAIL_FORWARD = createSoundEvent("entity/snail_forward");
    public static final RegistryObject<SoundEvent> SNAIL_BACK = createSoundEvent("entity/snail_back");
    public static final RegistryObject<SoundEvent> BUCKET_FILL_SNAIL = createSoundEvent("item/bucket_fill_snail");
    public static final RegistryObject<SoundEvent> BUCKET_EMPTY_SNAIL = createSoundEvent("item/bucket_empty_snail");
    public static final RegistryObject<SoundEvent> BIRD_HURT = createSoundEvent("entity/bird_hurt");
    public static final RegistryObject<SoundEvent> BIRD_DEATH = createSoundEvent("entity/bird_death");
    public static final RegistryObject<SoundEvent> BIRD_EAT = createSoundEvent("entity/bird_eat");
    public static final RegistryObject<SoundEvent> BIRD_FLY = createSoundEvent("entity/bird_fly");
    public static final RegistryObject<SoundEvent> BIRD_AMBIENT_BLUEJAY = createSoundEvent("entity/bird_ambient_bluejay");
    public static final RegistryObject<SoundEvent> BIRD_AMBIENT_CANARY = createSoundEvent("entity/bird_ambient_canary");
    public static final RegistryObject<SoundEvent> BIRD_AMBIENT_ROBIN = createSoundEvent("entity/bird_ambient_robin");
    public static final RegistryObject<SoundEvent> BIRD_AMBIENT_CARDINAL = createSoundEvent("entity/bird_ambient_cardinal");
    public static final RegistryObject<SoundEvent> BIRD_AMBIENT_FINCH = createSoundEvent("entity/bird_ambient_finch");
    public static final RegistryObject<SoundEvent> BIRD_AMBIENT_SPARROW = createSoundEvent("entity/bird_ambient_sparrow");
    public static final RegistryObject<SoundEvent> NAUTILUS_AMBIENT = createSoundEvent("entity/nautilus_ambient");
    public static final RegistryObject<SoundEvent> NAUTILUS_AMBIENT_ON_LAND = createSoundEvent("entity/nautilus_ambient_land");
    public static final RegistryObject<SoundEvent> NAUTILUS_DASH = createSoundEvent("entity/nautilus_dash");
    public static final RegistryObject<SoundEvent> NAUTILUS_DASH_ON_LAND = createSoundEvent("entity/nautilus_dash_land");
    public static final RegistryObject<SoundEvent> NAUTILUS_DASH_READY = createSoundEvent("entity/nautilus_dash_ready");
    public static final RegistryObject<SoundEvent> NAUTILUS_DASH_READY_ON_LAND = createSoundEvent("entity/nautilus_dash_ready_land");
    public static final RegistryObject<SoundEvent> NAUTILUS_DEATH = createSoundEvent("entity/nautilus_death");
    public static final RegistryObject<SoundEvent> NAUTILUS_DEATH_ON_LAND = createSoundEvent("entity/nautilus_death_land");
    public static final RegistryObject<SoundEvent> NAUTILUS_EAT = createSoundEvent("entity/nautilus_eat");
    public static final RegistryObject<SoundEvent> NAUTILUS_HURT = createSoundEvent("entity/nautilus_hurt");
    public static final RegistryObject<SoundEvent> NAUTILUS_HURT_ON_LAND = createSoundEvent("entity/nautilus_hurt_land");
    public static final RegistryObject<SoundEvent> NAUTILUS_SWIM = createSoundEvent("entity/nautilus_swim");
    public static final RegistryObject<SoundEvent> NAUTILUS_RIDING = createSoundEvent("entity/nautilus_riding");
    public static final RegistryObject<SoundEvent> BABY_NAUTILUS_AMBIENT = createSoundEvent("entity/baby_nautilus_ambient");
    public static final RegistryObject<SoundEvent> BABY_NAUTILUS_AMBIENT_ON_LAND = createSoundEvent("entity/baby_nautilus_ambient_land");
    public static final RegistryObject<SoundEvent> BABY_NAUTILUS_DEATH = createSoundEvent("entity/baby_nautilus_death");
    public static final RegistryObject<SoundEvent> BABY_NAUTILUS_DEATH_ON_LAND = createSoundEvent("entity/baby_nautilus_death_land");
    public static final RegistryObject<SoundEvent> BABY_NAUTILUS_EAT = createSoundEvent("entity/baby_nautilus_eat");
    public static final RegistryObject<SoundEvent> BABY_NAUTILUS_HURT = createSoundEvent("entity/baby_nautilus_hurt");
    public static final RegistryObject<SoundEvent> BABY_NAUTILUS_HURT_ON_LAND = createSoundEvent("entity/baby_nautilus_hurt_land");
    public static final RegistryObject<SoundEvent> BABY_NAUTILUS_SWIM = createSoundEvent("entity/baby_nautilus_swim");
    public static final RegistryObject<SoundEvent> ARMADILLO_EAT = createSoundEvent("entity/armadillo_eat");
    public static final RegistryObject<SoundEvent> ARMADILLO_HURT = createSoundEvent("entity/armadillo_hurt");
    public static final RegistryObject<SoundEvent> ARMADILLO_HURT_REDUCED = createSoundEvent("entity/armadillo_hurt_reduced");
    public static final RegistryObject<SoundEvent> ARMADILLO_AMBIENT = createSoundEvent("entity/armadillo_ambient");
    public static final RegistryObject<SoundEvent> ARMADILLO_STEP = createSoundEvent("entity/armadillo_step");
    public static final RegistryObject<SoundEvent> ARMADILLO_DEATH = createSoundEvent("entity/armadillo_death");
    public static final RegistryObject<SoundEvent> ARMADILLO_ROLL = createSoundEvent("entity/armadillo_roll");
    public static final RegistryObject<SoundEvent> ARMADILLO_LAND = createSoundEvent("entity/armadillo_land");
    public static final RegistryObject<SoundEvent> ARMADILLO_SCUTE_DROP = createSoundEvent("entity/armadillo_scute_drop");
    public static final RegistryObject<SoundEvent> ARMADILLO_UNROLL_FINISH = createSoundEvent("entity/armadillo_unroll_finish");
    public static final RegistryObject<SoundEvent> ARMADILLO_PEEK = createSoundEvent("entity/armadillo_peek");
    public static final RegistryObject<SoundEvent> ARMADILLO_UNROLL_START = createSoundEvent("entity/armadillo_unroll_start");
    public static final RegistryObject<SoundEvent> ARMADILLO_BRUSH = createSoundEvent("entity/armadillo_brush");
    public static final RegistryObject<SoundEvent> GHASTLING_AMBIENT = createSoundEvent("entity/ghastling_ambient");
    public static final RegistryObject<SoundEvent> GHASTLING_DEATH = createSoundEvent("entity/ghastling_death");
    public static final RegistryObject<SoundEvent> GHASTLING_HURT = createSoundEvent("entity/ghastling_hurt");
    public static final RegistryObject<SoundEvent> GHASTLING_SPAWN = createSoundEvent("entity/ghastling_spawn");
    public static final RegistryObject<SoundEvent> HAPPY_GHAST_AMBIENT = createSoundEvent("entity/happy_ghast_ambient");
    public static final RegistryObject<SoundEvent> HAPPY_GHAST_DEATH = createSoundEvent("entity/happy_ghast_death");
    public static final RegistryObject<SoundEvent> HAPPY_GHAST_HURT = createSoundEvent("entity/happy_ghast_hurt");
    public static final RegistryObject<SoundEvent> HAPPY_GHAST_RIDING = createSoundEvent("entity/happy_ghast_riding");
    public static final RegistryObject<SoundEvent> HARNESS_EQUIP = createSoundEvent("entity/happy_ghast_equip");
    public static final RegistryObject<SoundEvent> HARNESS_UNEQUIP = createSoundEvent("entity/happy_ghast_unequip");
    public static final RegistryObject<SoundEvent> HARNESS_GOGGLES_UP = createSoundEvent("entity/happy_ghast_harness_goggles_up");
    public static final RegistryObject<SoundEvent> HARNESS_GOGGLES_DOWN = createSoundEvent("entity/happy_ghast_harness_goggles_down");
    public static final RegistryObject<SoundEvent> COPPER_GOLEM_DEATH_EXPOSED = createSoundEvent("entity/copper_golem_death.exposed");
    public static final RegistryObject<SoundEvent> COPPER_GOLEM_DEATH_OXIDIZED = createSoundEvent("entity/copper_golem_death.oxidized");
    public static final RegistryObject<SoundEvent> COPPER_GOLEM_DEATH_UNAFFECTED = createSoundEvent("entity/copper_golem_death.unaffected");
    public static final RegistryObject<SoundEvent> COPPER_GOLEM_DEATH_WEATHERED = createSoundEvent("entity/copper_golem_death.weathered");
    public static final RegistryObject<SoundEvent> COPPER_GOLEM_HEAD_SPIN_EXPOSED = createSoundEvent("entity/copper_golem_head_spin.exposed");
    public static final RegistryObject<SoundEvent> COPPER_GOLEM_HEAD_SPIN_OXIDIZED = createSoundEvent("entity/copper_golem_head_spin.oxidized");
    public static final RegistryObject<SoundEvent> COPPER_GOLEM_HEAD_SPIN_UNAFFECTED = createSoundEvent("entity/copper_golem_head_spin.unaffected");
    public static final RegistryObject<SoundEvent> COPPER_GOLEM_HEAD_SPIN_WEATHERED = createSoundEvent("entity/copper_golem_head_spin.weathered");
    public static final RegistryObject<SoundEvent> COPPER_GOLEM_HURT_EXPOSED = createSoundEvent("entity/copper_golem_hurt.exposed");
    public static final RegistryObject<SoundEvent> COPPER_GOLEM_HURT_OXIDIZED = createSoundEvent("entity/copper_golem_hurt.oxidized");
    public static final RegistryObject<SoundEvent> COPPER_GOLEM_HURT_UNAFFECTED = createSoundEvent("entity/copper_golem_hurt.unaffected");
    public static final RegistryObject<SoundEvent> COPPER_GOLEM_HURT_WEATHERED = createSoundEvent("entity/copper_golem_hurt.weathered");
    public static final RegistryObject<SoundEvent> COPPER_GOLEM_STEP_EXPOSED = createSoundEvent("entity/copper_golem_step.exposed");
    public static final RegistryObject<SoundEvent> COPPER_GOLEM_STEP_OXIDIZED = createSoundEvent("entity/copper_golem_step.oxidized");
    public static final RegistryObject<SoundEvent> COPPER_GOLEM_STEP_UNAFFECTED = createSoundEvent("entity/copper_golem_step.unaffected");
    public static final RegistryObject<SoundEvent> COPPER_GOLEM_STEP_WEATHERED = createSoundEvent("entity/copper_golem_step.weathered");
    public static final RegistryObject<SoundEvent> COPPER_GOLEM_SPAWN = createSoundEvent("entity/copper_golem_spawn");
    public static final RegistryObject<SoundEvent> COPPER_GOLEM_BECOME_STATUE = createSoundEvent("entity/become_statue");
    public static final RegistryObject<SoundEvent> COPPER_GOLEM_SHEAR = createSoundEvent("entity/copper_golem_shear");
    public static final RegistryObject<SoundEvent> COPPER_GOLEM_ITEM_DROP = createSoundEvent("entity/copper_golem_item_drop");
    public static final RegistryObject<SoundEvent> COPPER_GOLEM_ITEM_NO_DROP = createSoundEvent("entity/copper_golem_item_no_drop");
    public static final RegistryObject<SoundEvent> COPPER_GOLEM_ITEM_GET = createSoundEvent("entity/copper_golem_no_item_get");
    public static final RegistryObject<SoundEvent> COPPER_GOLEM_ITEM_NO_GET = createSoundEvent("entity/copper_golem_no_item_no_get");


    public static final RegistryObject<SoundEvent> CROCK_POT_CLOSE = createSoundEvent("block/crock_pot_close");
    public static final RegistryObject<SoundEvent> CROCK_POT_OPEN = createSoundEvent("block/crock_pot_open");
    public static final RegistryObject<SoundEvent> CROCK_POT_FINISH = createSoundEvent("block/crock_pot_finish");
    public static final RegistryObject<SoundEvent> CROCK_POT_RATTLE = createSoundEvent("block/crock_pot_rattle");
    public static final RegistryObject<SoundEvent> TORTOISE_EGG_BREAK = createSoundEvent("block/tortoise_egg_break");
    public static final RegistryObject<SoundEvent> TORTOISE_EGG_CRACK = createSoundEvent("block/tortoise_egg_crack");
    public static final RegistryObject<SoundEvent> TORTOISE_EGG_HATCH = createSoundEvent("block/tortoise_egg_hatch");
    public static final RegistryObject<SoundEvent> EYEBLOSSOM_OPEN_LONG = createSoundEvent("block/eyeblossom_open_long");
    public static final RegistryObject<SoundEvent> EYEBLOSSOM_OPEN = createSoundEvent("block/eyeblossom_open");
    public static final RegistryObject<SoundEvent> EYEBLOSSOM_CLOSE_LONG = createSoundEvent("block/eyeblossom_close_long");
    public static final RegistryObject<SoundEvent> EYEBLOSSOM_CLOSE = createSoundEvent("block/eyeblossom_close");
    public static final RegistryObject<SoundEvent> EYEBLOSSOM_IDLE = createSoundEvent("block/eyeblossom_idle");
    public static final RegistryObject<SoundEvent> PALE_HANGING_MOSS_IDLE = createSoundEvent("block/pale_hanging_moss_idle");
    public static final RegistryObject<SoundEvent> CREAKING_HEART_BREAK = createSoundEvent("block/creaking_heart_break");
    public static final RegistryObject<SoundEvent> CREAKING_HEART_FALL = createSoundEvent("block/creaking_heart_fall");
    public static final RegistryObject<SoundEvent> CREAKING_HEART_HIT = createSoundEvent("block/creaking_heart_hit");
    public static final RegistryObject<SoundEvent> CREAKING_HEART_HURT = createSoundEvent("block/creaking_heart_hurt");
    public static final RegistryObject<SoundEvent> CREAKING_HEART_PLACE = createSoundEvent("block/creaking_heart_place");
    public static final RegistryObject<SoundEvent> CREAKING_HEART_STEP = createSoundEvent("block/creaking_heart_step");
    public static final RegistryObject<SoundEvent> CREAKING_HEART_IDLE = createSoundEvent("block/creaking_heart_idle");
    public static final RegistryObject<SoundEvent> RESIN_BREAK = createSoundEvent("block/resin_break");
    public static final RegistryObject<SoundEvent> RESIN_FALL = createSoundEvent("block/resin_fall");
    public static final RegistryObject<SoundEvent> RESIN_PLACE = createSoundEvent("block/resin_place");
    public static final RegistryObject<SoundEvent> RESIN_STEP = createSoundEvent("block/resin_step");
    public static final RegistryObject<SoundEvent> RESIN_BRICKS_BREAK = createSoundEvent("block/resin_bricks_break");
    public static final RegistryObject<SoundEvent> RESIN_BRICKS_FALL = createSoundEvent("block/resin_bricks_fall");
    public static final RegistryObject<SoundEvent> RESIN_BRICKS_HIT = createSoundEvent("block/resin_bricks_hit");
    public static final RegistryObject<SoundEvent> RESIN_BRICKS_PLACE = createSoundEvent("block/resin_bricks_place");
    public static final RegistryObject<SoundEvent> RESIN_BRICKS_STEP = createSoundEvent("block/resin_bricks_step");
    public static final RegistryObject<SoundEvent> DRIED_GHAST_BREAK = createSoundEvent("block/dried_ghast_break");
    public static final RegistryObject<SoundEvent> DRIED_GHAST_STEP = createSoundEvent("block/dried_ghast_step");
    public static final RegistryObject<SoundEvent> DRIED_GHAST_FALL = createSoundEvent("block/dried_ghast_fall");
    public static final RegistryObject<SoundEvent> DRIED_GHAST_AMBIENT = createSoundEvent("block/dried_ghast_ambient");
    public static final RegistryObject<SoundEvent> DRIED_GHAST_AMBIENT_WATER = createSoundEvent("block/dried_ghast_ambient_water");
    public static final RegistryObject<SoundEvent> DRIED_GHAST_PLACE = createSoundEvent("block/dried_ghast_place");
    public static final RegistryObject<SoundEvent> DRIED_GHAST_PLACE_IN_WATER = createSoundEvent("block/dried_ghast_place_in_water");
    public static final RegistryObject<SoundEvent> DRIED_GHAST_TRANSITION = createSoundEvent("block/dried_ghast_transition");
    public static final RegistryObject<SoundEvent> LEAF_LITTER_BREAK = createSoundEvent("block/leaf_litter_break");
    public static final RegistryObject<SoundEvent> LEAF_LITTER_STEP = createSoundEvent("block/leaf_litter_step");
    public static final RegistryObject<SoundEvent> LEAF_LITTER_PLACE = createSoundEvent("block/leaf_litter_place");
    public static final RegistryObject<SoundEvent> LEAF_LITTER_HIT = createSoundEvent("block/leaf_litter_hit");
    public static final RegistryObject<SoundEvent> LEAF_LITTER_FALL = createSoundEvent("block/leaf_litter_fall");
    public static final RegistryObject<SoundEvent> CACTUS_FLOWER_BREAK = createSoundEvent("block/cactus_flower_break");
    public static final RegistryObject<SoundEvent> CACTUS_FLOWER_PLACE = createSoundEvent("block/cactus_flower_place");
    public static final RegistryObject<SoundEvent> FIREFLY_BUSH_IDLE = createSoundEvent("block/firefly_bush_idle");
    public static final RegistryObject<SoundEvent> SAND_IDLE = createSoundEvent("block/sand_idle");
    public static final RegistryObject<SoundEvent> DEAD_BUSH_IDLE = createSoundEvent("block/deadbush_idle");
    public static final RegistryObject<SoundEvent> DRY_GRASS = createSoundEvent("block/dry_grass_ambient");
    public static final RegistryObject<SoundEvent> COPPER_CHEST_CLOSE = createSoundEvent("block/copper_chest_close");
    public static final RegistryObject<SoundEvent> COPPER_CHEST_OPEN = createSoundEvent("block/copper_chest_open");
    public static final RegistryObject<SoundEvent> COPPER_STATUE_BREAK = createSoundEvent("block/copper_statue_break");
    public static final RegistryObject<SoundEvent> COPPER_STATUE_PLACE = createSoundEvent("block/copper_statue_place");
    public static final RegistryObject<SoundEvent> COPPER_STATUE_HIT = createSoundEvent("block/copper_statue_hit");
    public static final RegistryObject<SoundEvent> COPPER_STATUE_BECOME = createSoundEvent("block/become_statue");
//    public static final RegistryObject<SoundEvent> COPPER_TRAPDOOR_CLOSE = createSoundEvent("block/copper_trapdoor_close");
//    public static final RegistryObject<SoundEvent> COPPER_TRAPDOOR_OPEN = createSoundEvent("block/copper_trapdoor_open");
    public static final RegistryObject<SoundEvent> COPPER_BULB_TURN_ON = createSoundEvent("block/copper_bulb_turn_on");
    public static final RegistryObject<SoundEvent> COPPER_BULB_TURN_OFF = createSoundEvent("block/copper_bulb_turn_off");
    public static final RegistryObject<SoundEvent> COPPER_GRATE_BREAK = createSoundEvent("block/copper_grate_break");
    public static final RegistryObject<SoundEvent> COPPER_GRATE_FALL = createSoundEvent("block/copper_grate_fall");
    public static final RegistryObject<SoundEvent> COPPER_GRATE_HIT = createSoundEvent("block/copper_grate_hit");
    public static final RegistryObject<SoundEvent> COPPER_GRATE_PLACE = createSoundEvent("block/copper_grate_place");
    public static final RegistryObject<SoundEvent> COPPER_GRATE_STEP = createSoundEvent("block/copper_grate_step");
    public static final RegistryObject<SoundEvent> COPPER_DOOR_CLOSE_SOUND = createSoundEvent("block/copper_door_close");
    public static final RegistryObject<SoundEvent> COPPER_DOOR_OPEN_SOUND = createSoundEvent("block/copper_door_open");
    public static final RegistryObject<SoundEvent> COPPER_TRAPDOOR_CLOSE_SOUND = createSoundEvent("block/copper_trapdoor_close");
    public static final RegistryObject<SoundEvent> COPPER_TRAPDOOR_OPEN_SOUND = createSoundEvent("block/copper_trapdoor_open");


    public static final RegistryObject<SoundEvent> ICE_CUBES_EAT = createSoundEvent("item/ice_cubes_eat");
    public static final RegistryObject<SoundEvent> ICE_CREAM_EAT = createSoundEvent("item/ice_cream_eat");
    public static final RegistryObject<SoundEvent> BANANA_BUNCH_OPEN = createSoundEvent("item/banana_bunch_open");
    public static final RegistryObject<SoundEvent> NAUTILUS_SADDLE_UNDERWATER_EQUIP = createSoundEvent("item/nautilus_saddle_underwater_equip");
    public static final RegistryObject<SoundEvent> NAUTILUS_SADDLE_EQUIP = createSoundEvent("item/nautilus_saddle_equip");
    public static final RegistryObject<SoundEvent> ARMOR_EQUIP_COPPER = createSoundEvent("item/armor_equip_copper");


    public static final RegistryObject<SoundEvent> WEATHER_END_FLASH = createSoundEvent("weather.end_flash");


    public static final RegistryObject<SoundEvent> SALT_BREAK = createSaltSoundEvent("salt.break");
    public static final RegistryObject<SoundEvent> SALT_STEP = createSaltSoundEvent("salt.step");
    public static final RegistryObject<SoundEvent> SALT_PLACE = createSaltSoundEvent("salt.place");
    public static final RegistryObject<SoundEvent> SALT_HIT = createSaltSoundEvent("salt.hit");
    public static final RegistryObject<SoundEvent> SALT_FALL = createSaltSoundEvent("salt.fall");
    public static final RegistryObject<SoundEvent> SALT_CLUSTER_BREAK = createSaltSoundEvent("salt_cluster.break");
    public static final RegistryObject<SoundEvent> SALT_CLUSTER_STEP = createSaltSoundEvent("salt_cluster.step");
    public static final RegistryObject<SoundEvent> SALT_CLUSTER_PLACE = createSaltSoundEvent("salt_cluster.place");
    public static final RegistryObject<SoundEvent> SALT_CLUSTER_HIT = createSaltSoundEvent("salt_cluster.hit");
    public static final RegistryObject<SoundEvent> SALT_CLUSTER_FALL = createSaltSoundEvent("salt_cluster.fall");
    public static final RegistryObject<SoundEvent> LARGE_SALT_BUD_BREAK = createSaltSoundEvent("large_salt_bud.break");
    public static final RegistryObject<SoundEvent> LARGE_SALT_BUD_STEP = createSaltSoundEvent("large_salt_bud.step");
    public static final RegistryObject<SoundEvent> LARGE_SALT_BUD_PLACE = createSaltSoundEvent("large_salt_bud.place");
    public static final RegistryObject<SoundEvent> LARGE_SALT_BUD_HIT = createSaltSoundEvent("large_salt_bud.hit");
    public static final RegistryObject<SoundEvent> LARGE_SALT_BUD_FALL = createSaltSoundEvent("large_salt_bud.fall");
    public static final RegistryObject<SoundEvent> MEDIUM_SALT_BUD_BREAK = createSaltSoundEvent("medium_salt_bud.break");
    public static final RegistryObject<SoundEvent> MEDIUM_SALT_BUD_STEP = createSaltSoundEvent("medium_salt_bud.step");
    public static final RegistryObject<SoundEvent> MEDIUM_SALT_BUD_PLACE = createSaltSoundEvent("medium_salt_bud.place");
    public static final RegistryObject<SoundEvent> MEDIUM_SALT_BUD_HIT = createSaltSoundEvent("medium_salt_bud.hit");
    public static final RegistryObject<SoundEvent> MEDIUM_SALT_BUD_FALL = createSaltSoundEvent("medium_salt_bud.fall");
    public static final RegistryObject<SoundEvent> SMALL_SALT_BUD_BREAK = createSaltSoundEvent("small_salt_bud.break");
    public static final RegistryObject<SoundEvent> SMALL_SALT_BUD_STEP = createSaltSoundEvent("small_salt_bud.step");
    public static final RegistryObject<SoundEvent> SMALL_SALT_BUD_PLACE = createSaltSoundEvent("small_salt_bud.place");
    public static final RegistryObject<SoundEvent> SMALL_SALT_BUD_HIT = createSaltSoundEvent("small_salt_bud.hit");
    public static final RegistryObject<SoundEvent> SMALL_SALT_BUD_FALL = createSaltSoundEvent("small_salt_bud.fall");
    public static final RegistryObject<SoundEvent> SALT_DISSOLVE = createSaltSoundEvent("salt.dissolve");
    public static final RegistryObject<SoundEvent> MELT = createSaltSoundEvent("melt");
    public static final RegistryObject<SoundEvent> CAULDRON_EVAPORATE = createSaltSoundEvent("cauldron.evaporate");
    public static final RegistryObject<SoundEvent> SALT_BUBBLE_POP = createSaltSoundEvent("bubble_pop");
    public static final RegistryObject<SoundEvent> SALT_CAULDRON_REMOVE_SALT = createSaltSoundEvent("salt_cauldron.remove_salt");

    public static final SoundType SALT = new ForgeSoundType(1.0f, 1.0f, SALT_BREAK, SALT_STEP, SALT_PLACE, SALT_HIT, SALT_FALL);
    public static final SoundType SALT_CLUSTER = new ForgeSoundType(1.0f, 1.0f, SALT_CLUSTER_BREAK, SALT_CLUSTER_STEP, SALT_CLUSTER_PLACE, SALT_CLUSTER_HIT, SALT_CLUSTER_FALL);
    public static final SoundType LARGE_SALT_BUD = new ForgeSoundType(1.0f, 1.0f, LARGE_SALT_BUD_BREAK, LARGE_SALT_BUD_STEP, LARGE_SALT_BUD_PLACE, LARGE_SALT_BUD_HIT, LARGE_SALT_BUD_FALL);
    public static final SoundType MEDIUM_SALT_BUD = new ForgeSoundType(1.0f, 1.0f, MEDIUM_SALT_BUD_BREAK, MEDIUM_SALT_BUD_STEP, MEDIUM_SALT_BUD_PLACE, MEDIUM_SALT_BUD_HIT, MEDIUM_SALT_BUD_FALL);
    public static final SoundType SMALL_SALT_BUD = new ForgeSoundType(1.0f, 1.0f, SMALL_SALT_BUD_BREAK, SMALL_SALT_BUD_STEP, SMALL_SALT_BUD_PLACE, SMALL_SALT_BUD_HIT, SMALL_SALT_BUD_FALL);
    public static final SoundType CREAKING_HEART = new ForgeSoundType(1.0f, 1.0f, CREAKING_HEART_BREAK, CREAKING_HEART_STEP, CREAKING_HEART_PLACE, CREAKING_HEART_HIT, CREAKING_HEART_FALL);
    public static final SoundType RESIN = new ForgeSoundType(1.0f, 1.0f, RESIN_BREAK, RESIN_STEP, RESIN_PLACE, () -> SoundEvents.EMPTY, RESIN_FALL);
    public static final SoundType RESIN_BRICKS = new ForgeSoundType(1.0f, 1.0f, RESIN_BRICKS_BREAK, RESIN_BRICKS_STEP, RESIN_BRICKS_PLACE, RESIN_BRICKS_HIT, RESIN_BRICKS_FALL);
    public static final SoundType DRIED_GHAST = new ForgeSoundType(1.0f, 1.0f, DRIED_GHAST_BREAK, DRIED_GHAST_STEP, () -> SoundEvents.EMPTY, () -> SoundEvents.EMPTY, DRIED_GHAST_FALL);
    public static final SoundType LEAF_LITTER = new ForgeSoundType(1.0f, 1.0f, LEAF_LITTER_BREAK, LEAF_LITTER_STEP, LEAF_LITTER_PLACE, LEAF_LITTER_HIT, LEAF_LITTER_FALL);
    public static final SoundType CACTUS_FLOWER = new ForgeSoundType(1.0f, 1.0f, CACTUS_FLOWER_BREAK, () -> SoundEvents.EMPTY, CACTUS_FLOWER_PLACE, () -> SoundEvents.EMPTY, () -> SoundEvents.EMPTY);
    public static final SoundType COPPER_STATUE = new ForgeSoundType(1.0F, 1.0F, (Supplier<SoundEvent>) COPPER_STATUE_BREAK, COPPER_STATUE_PLACE, COPPER_STATUE_PLACE, COPPER_STATUE_HIT, COPPER_STATUE_PLACE);
    public static final SoundType COPPER_GRATE = new ForgeSoundType(1.0F, 1.0F, COPPER_GRATE_BREAK, COPPER_GRATE_STEP, COPPER_GRATE_PLACE, COPPER_GRATE_HIT, COPPER_GRATE_FALL);


    private static RegistryObject<SoundEvent> createSoundEvent(final String soundName) {
        return SOUND_EVENTS.register(soundName, () -> SoundEvent.createVariableRangeEvent(Utils.createResourceLocation(soundName)));
    }

    private static RegistryObject<SoundEvent> createSaltSoundEvent(String name) {
        return SOUND_EVENTS.register("block.salt." + name, () -> SoundEvent.createVariableRangeEvent(Utils.createResourceLocation("block.salt." + name)));
    }
}
